In [2]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score

In [17]:
df_main=pd.read_csv('horse.csv')
df=df_main
df.head()

,surgery,age,hospital_number,rectal_temp,pulse,respiratory_rate,temp_of_extremities,peripheral_pulse,mucous_membrane,capillary_refill_time,...,packed_cell_volume,total_protein,abdomo_appearance,abdomo_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
0,no,adult,530101,38.5,66.0,28.0,cool,reduced,NaN,more_3_sec,...,45.0,8.4,NaN,NaN,died,no,11300,0,0,no
1,yes,adult,534817,39.2,88.0,20.0,NaN,NaN,pale_cyanotic,less_3_sec,...,50.0,85.0,cloudy,2.0,euthanized,no,2208,0,0,no
2,no,adult,530334,38.3,40.0,24.0,normal,normal,pale_pink,less_3_sec,...,33.0,6.7,NaN,NaN,lived,no,0,0,0,yes
3,yes,young,5290409,39.1,164.0,84.0,cold,normal,dark_cyanotic,more_3_sec,...,48.0,7.2,serosanguious,5.3,died,yes,2208,0,0,yes
4,no,adult,530255,37.3,104.0,35.0,NaN,NaN,dark_cyanotic,more_3_sec,...,74.0,7.4,NaN,NaN,died,no,4300,0,0,no

Q NO 1

In [18]:
df.isnull().values.any()

True

Q NO 2

In [19]:
X=df.drop('outcome',axis=1)
y=df['outcome']

In [20]:
X=pd.get_dummies(X)

Q NO 3

In [21]:
X=X.fillna(X.mode().iloc[0])
X     # it fills with mode value of columns

,hospital_number,rectal_temp,pulse,respiratory_rate,nasogastric_reflux_ph,packed_cell_volume,total_protein,abdomo_protein,lesion_1,lesion_2,...,abdomen_firm,abdomen_normal,abdomen_other,abdomo_appearance_clear,abdomo_appearance_cloudy,abdomo_appearance_serosanguious,surgical_lesion_no,surgical_lesion_yes,cp_data_no,cp_data_yes
0,530101,38.5,66.0,28.0,2.0,45.0,8.4,2.0,11300,0,...,0,0,0,0,0,0,1,0,1,0
1,534817,39.2,88.0,20.0,2.0,50.0,85.0,2.0,2208,0,...,0,0,1,0,1,0,1,0,1,0
2,530334,38.3,40.0,24.0,2.0,33.0,6.7,2.0,0,0,...,0,1,0,0,0,0,1,0,0,1
3,5290409,39.1,164.0,84.0,5.0,48.0,7.2,5.3,2208,0,...,0,0,0,0,0,1,0,1,0,1
4,530255,37.3,104.0,35.0,2.0,74.0,7.4,2.0,4300,0,...,0,0,0,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,533886,38.0,120.0,70.0,2.0,55.0,65.0,2.0,3205,0,...,0,0,0,0,0,0,1,0,1,0
295,527702,37.2,72.0,24.0,2.0,44.0,6.5,3.3,2208,0,...,0,0,0,0,0,1,0,1,0,1
296,529386,37.5,72.0,30.0,2.0,60.0,6.8,2.0,3205,0,...,0,0,0,0,0,0,0,1,1,0
297,530612,36.5,100.0,24.0,2.0,50.0,6.0,3.4,2208,0,...,0,0,0,0,0,1,0,1,0,1
298,534618,37.2,40.0,20.0,2.0,36.0,62.0,1.0,6112,0,...,0,1,0,1,0,0,1,0,1,0

Q NO 4

In [22]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=45,test_size=0.2,stratify=y)

In [24]:
dt.fit(X_train,y_train)

DecisionTreeClassifier()

In [25]:
y_pred=dt.predict(X_test)

In [26]:
accuracy_score(y_test,y_pred)

0.65

Q NO 5

In [13]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()

In [30]:
rfc.fit(X_train,y_train)

RandomForestClassifier()

In [31]:
y_predrfc=rfc.predict(X_test)

In [32]:
accuracy_score(y_test,y_predrfc)

0.7

random forest has more accuracy

END